model:
  type: "random_forest"  # Có thể là: random_forest, svm, neural_network, etc.
  params:
    random_forest:
      n_estimators: 100
      max_depth: 10
      min_samples_split: 2
      min_samples_leaf: 1
    svm:
      C: 1.0
      kernel: "rbf"
      gamma: "scale"
    neural_network:
      hidden_layers: [128, 64]
      activation: "relu"
      learning_rate: 0.001
      batch_size: 32
      epochs: 50

preprocessing:
  scaling: "standard"  # Có thể là: standard, minmax, robust
  categorical_encoding: "one_hot"  # Có thể là: one_hot, label
  missing_values: "mean"  # Có thể là: mean, median, most_frequent

training:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  cross_validation_folds: 5

evaluation:
  metrics: ["accuracy", "precision", "recall", "f1"]